### ISSUE TITLE
Both Abstracts named "Zusammenfassung"

### ISSUE THREAD

**Issue by JEPA1002** [matteodelucchi/ZHAW_thesis-template#12]
If the language is set to ngerman, both Abstract's will have the name "Zusammenfassung", instead of one Abstract and one Zusammenfassung.

If the language is set to english one is name Abstract and the other Zusammenfassung

**Comment by matteodelucchi** [comment]
:wave: @JEPA1002 
Thanks for reporting this bug!
Could you double-check to see if it works as expected now? 
Cheers, Matteo

**Comment by JEPA1002** [comment]
@matteodelucchi 
Thanks for fixing it so quickly now it works as expected
many thanks :)
